routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
 */

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/', ['uses' => 'IndexController@index', 'as' => 'index']);

Auth::routes();

//Подтверждение регистрации
Route::get('/confirm/{id}/{code}', ['uses' => 'Auth\RegisterController@confirmRegistration', 'as' => 'confirm']);

//Аутентификация, переопределенные роуты
// Вызов страницы регистрации пользователя
Route::get('/register', ['uses' => 'Auth\RegisterController@showRegistrationForm', 'as' => 'register']);

// Вызов формы ввода e-mail для сброса пароля
Route::get('/password/reset', ['uses' => 'Auth\ForgotPasswordController@showLinkRequestForm', 'as' => 'password.reset']);

// Вызов формы ввода нового пароля при сбросе
Route::get('/password/reset/{token}', ['uses' => 'Auth\ResetPasswordController@showResetForm', 'as' => 'password.token']);

// При запрещенном к просмотру разделе
Route::get('noaccess', ['uses' => 'Auth\NoaccessController@noaccess', 'as' => 'noaccess']);

Route::get('/home', 'HomeController@index');

//Пользователи
Route::resource('users', 'UserController');
Route::post('users/search', ['uses' => 'UserController@search', 'as' => 'users.search']);
Route::post('users/{user}/password', ['uses' => 'UserController@changePassword', 'as' => 'users.password']);
Route::get('users/{users}/newscomments', ['uses' => 'UserController@newsComments', 'as' => 'users.newscomments']);
Route::get('users/{users}/nominations', ['uses' => 'UserController@getUserNominations', 'as' => 'users.nominations']);
Route::get('users/comments/{user}', ['uses' => 'UserController@comments', 'as' => 'users.comments']);

// Обратная связь

Route::resource('feedback', 'FeedbackController');
Route::post('feedback/send', ['uses' => 'FeedbackController@send', 'as' => 'feedback.send']);

//Новости

Route::resource('news', 'NewsController');
Route::post('news/{news}/{user}/addcomment', ['uses' => 'NewsController@addComment', 'as' => 'news.addcomment']);

//Номинация

Route::resource('nomination', 'NominationController');
Route::get('nomination/{nomination}/competitors', ['uses' => 'NominationController@getCompetitors', 'as' => 'nomination.competitors']);
Route::get('nomination/{nomination}/description', ['uses' => 'NominationController@showDescription', 'as' => 'nomination.description']);
Route::get('nomination/{nomination}/photos', ['uses' => 'NominationController@photos', 'as' => 'nomination.photos']);
Route::get('nomination/{nomination}/{agree?}', ['uses' => 'NominationController@show', 'as' => 'nomination.show']);

// Competitors

Route::resource('competitor', 'CompetitorController');
Route::post('competitor/{nomination}/create', ['uses' => 'CompetitorController@create', 'as' => 'competitor.create']);
//Route::post('competitor/search', ['uses' => 'CompetitorController@search', 'as' => 'competitor.search']);
Route::post('competitor', ['uses' => 'CompetitorController@index', 'as' => 'competitor.search']);
Route::get('champion', ['uses' => 'CompetitorController@champions', 'as' => 'champion']);


//Фотогалерея

Route::resource('photo', 'PhotoController');
Route::post('photo/{competitor}/{nomination}', ['uses' => 'PhotoController@store', 'as' => 'photo.store']); // основное фото
Route::post('photo/{competitor}/{nomination}/addition', ['uses' => 'PhotoController@storeAddition', 'as' => 'photo.store.addition']); // дополнительное фото
Route::get('photo/confirm/addition/{competitor}/{photo}', ['uses' => 'PhotoController@confirmAddition', 'as' => 'photo.confirm.addition']); // дополнительное фото, подтверждение публикации
Route::post('photo/search', ['uses' => 'PhotoController@index', 'as' => 'photo.search']);

//Комментарии

Route::resource('comment', 'CommentController');
Route::post('comment/add/news/{instance}/{user}', ['uses' => 'CommentController@storeCommentNews', 'as' => 'comment.store.news']);
Route::post('comment/add/competitor/{instance}/{user}', ['uses' => 'CommentController@storeCommentCompetitor', 'as' => 'comment.store.competitor']);
Route::post('comment/add/photo/{instance}/{user}', ['uses' => 'CommentController@storeCommentPhoto', 'as' => 'comment.store.photo']);
Route::post('comment/add/nomination/{instance}/{user}', ['uses' => 'CommentController@storeCommentNomination', 'as' => 'comment.store.nomination']);
Route::get('comment/info/{comment}/{user}', ['uses' => 'CommentController@infoModerator', 'as' => 'comment.info.moderator']);

// Лайки

Route::resource('like', 'LikeController');
Route::get('likes/buy/{user}', ['uses' => 'LikeController@buy', 'as' => 'like.buy']);
Route::post('likes/add', ['uses' => 'LikeController@add', 'as' => 'like.add']);
Route::get('like/create/{photo}', ['uses' => 'LikeController@create', 'as' => 'like.create']);
Route::get('likes/{photo}', ['uses' => 'LikeController@likes', 'as' => 'like.likes']);

// Судейство

Route::resource('referee', 'RefereeController');
Route::get('referee/score/{competitor}', ['uses' => 'RefereeController@score', 'as' => 'referee.score']);
Route::post('referee/score/{competitor}', ['uses' => 'RefereeController@storeScore', 'as' => 'referee.score.store']);

// Призовой фонд

Route::resource('fund', 'FundController');

// Рейтинг

Route::resource('rating', 'RatingController');
Route::get('rating/score/{nomination}', ['uses' => 'RatingController@showRatingScore', 'as' => 'rating.score']);
Route::get('rating/like/{nomination}', ['uses' => 'RatingController@showRatingLike', 'as' => 'rating.like']);

// Обработка персональных данных

Route::get('/personal-data', ['uses' => 'ContentController@showPersonalData', 'as' => 'personal_data.index']);

// Подробно о сайте

Route::get('/site-description', ['uses' => 'ContentController@showSiteDescription', 'as' => 'site_description']);

// Пользовательское соглашение

Route::get('/user-agreement', ['uses' => 'ContentController@showUserAgreement', 'as' => 'user_agreement']);

// Справка

Route::get('/help', ['uses' => 'ContentController@showHelp', 'as' => 'help']);

//Cookies

Route::post('/cookie/index/informer', ['uses' => 'CookieController@setCookieIndexInformer', 'as' => 'cookie.index.informer']);
Route::post('/cookie/nomination/informer', ['uses' => 'CookieController@setCookieNominationInformer', 'as' => 'cookie.nomination.informer']);
Route::post('/cookie/photos/informer', ['uses' => 'CookieController@setCookiePhotosInformer', 'as' => 'cookie.photos.informer']);
Route::post('/cookie/competitors/informer', ['uses' => 'CookieController@setCookieCompetitorsInformer', 'as' => 'cookie.competitors.informer']);
Route::post('/cookie/competitor/edit/informer', ['uses' => 'CookieController@setCookieCompetitorEditInformer', 'as' => 'cookie.competitor.edit.informer']);
Route::post('/cookie/competitor/informer', ['uses' => 'CookieController@setCookieCompetitorInformer', 'as' => 'cookie.competitor.informer']);
Route::post('/cookie/funds/informer', ['uses' => 'CookieController@setCookieFundsInformer', 'as' => 'cookie.funds.informer']);
Route::post('/cookie/likebuy/informer', ['uses' => 'CookieController@setCookieLikebuyInformer', 'as' => 'cookie.likebuy.informer']);
Route::post('/cookie/photo/informer', ['uses' => 'CookieController@setCookiePhotoInformer', 'as' => 'cookie.photo.informer']);
Route::post('/cookie/ratings/informer', ['uses' => 'CookieController@setCookieRatingsInformer', 'as' => 'cookie.ratings.informer']);
Route::post('/cookie/rating/likes/informer', ['uses' => 'CookieController@setCookieRatingLikesInformer', 'as' => 'cookie.rating.likes.informer']);
Route::post('/cookie/rating/scores/informer', ['uses' => 'CookieController@setCookieRatingScoresInformer', 'as' => 'cookie.rating.scores.informer']);
Route::post('/cookie/users/informer', ['uses' => 'CookieController@setCookieUsersInformer', 'as' => 'cookie.users.informer']);
Route::post('/cookie/user/edit/informer', ['uses' => 'CookieController@setCookieUserEditInformer', 'as' => 'cookie.user.edit.informer']);
Route::post('/cookie/user/informer', ['uses' => 'CookieController@setCookieUserInformer', 'as' => 'cookie.user.informer']);

//Платежные системы

//Форма оплаты за участие в номинации
Route::get('/payment/yandexmoney/{nomination}', ['uses' => 'Payment\YandexMoneyController@showFormNomination', 'as' => 'payment.yandexmoney.nomination']);
//Страница перехода с платежной системы при оплате участия в номинации
//Route::get('/payment/yandexmoney/recive/nomination/{nomination}', ['uses' => 'Payment\YandexMoneyController@recivePaymentNomination', 'as' => 'payment.yandexmoney.recive.nomination']);
//Форма оплаты загрузки дополнительных фото
Route::get('/payment/yandexmoney/{nomination}/additionalphoto', ['uses' => 'Payment\YandexMoneyController@showFormAdditionalPhoto', 'as' => 'payment.yandexmoney.additionalphoto']);


// Верстка

Route::group(['middleware' => 'makeup'], function () {

    Route::get('/template', function () {
        return view('makeup.template');
    });

    Route::get('/makeup/feedback', function () {
        return view('makeup.feedback');
    });

    Route::get('/makeup/nomination-index', function () {
        return view('makeup.nomination-index');
    });

    Route::get('/makeup/nomination-show', function () {
        return view('makeup.nomination-show');
    });

// Верстка jasny

    Route::get('/makeup/jasny', function () {
        return view('makeup.jasny');
    });

    Route::get('/makeup/main', function () {
        return view('makeup.main');
    });

    Route::get('/makeup/index', function () {
        return view('makeup.index');
    });

    Route::get('/makeup/text', function () {
        return view('makeup.text');
    });

    Route::get('/makeup/content', function () {

resources/views/home.blade.php
@extends('layouts.layout')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('layouts.bibikini')
{{--@section('breadcrumbs')
    <ol class="breadcrumb">
        <li class="active">Главная</li>
    </ol>
@endsection --}}
{{-- @section('header')
    <h1>На старт! <small></small></h1>
@endsection --}}
@section('informer')
  @if (!Cookie::get('informer-index') )
    @include('widget.informer',['contents' => $contents, 'content_key'=>'index_quick_start_1', 'cookie_url'=>'/cookie/index/informer'])
  @endif
  {{--@php
  $informer_index = false;
  if(isset($_COOKIE['informer-index'])) {
    $informer_index = true;
  }
  @endphp

  @if (!$informer_index)
    @include('widget.informer',['contents' => $contents, 'content_key'=>'index_quick_start_1'])
  @endif--}}
@endsection


@section('content')
{{-- <div class="row">
          <div class="col-lg-12">
          <h3>Главные новости</h3>
        </div>
      @foreach ($important_news as $important_new)
        <div class="col-md-4 col-sm-4">
          <div class="jumbotron {{$important_new->important_styles}}">
              <a href="{{route('news.show', [$important_new->id])}}">
                  <img class="img-thumbnail img-responsive" src="{{$important_new->pic}}"/>
              </a>
              <p>
                  <a href="{{route('news.show', [$important_new->id])}}">
                    {{$important_new->important_intro}}
                  </a>
              </p>
              <p class="text-center">
                  <a href="{{route('news.show', [$important_new->id])}}" class="btn {{$important_new->important_button_style}} btn-lg btn-nommi" role="button">{!! $important_new->important_button_icon !!}&nbsp;{{$important_new->important_button_text}}</a>
              </p>

          </div>
        </div>
      @endforeach
</div> --}}


<div class="row">
  <div class="col-lg-12">
  <h3>Номинации <small></small></h3>
</div>
@foreach ($nominations as $nomination)
           <div class="col-md-3 col-sm-6">
               <div class="jumbotron nomination">
                   <div class="header {{$nomination->css_header}}
                     @if ($nomination->status == 3)
                      closed
                    @endif
                     ">
                       <div class="block">
                           <img class="img-responsive pull-left" src="{{asset($nomination->pic)}}"/>
                       </div>
                       <div class="block">
                           <h3 class="pull-left">{!! $nomination->name !!}</h3>
                       </div>
                  </div>
                  <div class="description">
                  <div class="block sex {{$nomination->css_header}}">
                      {!!$nomination->type_icon!!}
                      <small>{{$nomination->count_competitors}}</small>
                  </div>
                  <div class="block prize">
                      <i class="fa fa-trophy" aria-hidden="true"></i>
                      @if (!empty($nomination->fundsScores->sum))
                       <small>{{$nomination->fundsScores->sum}}</small>
                      @else
                        <small></small>
                      @endif
                  </div>
                  <div class="block like">
                      <i class="fa fa-heart" aria-hidden="true"></i>
                      @if (!empty($nomination->fundsLikes->sum))
                       <small>{{$nomination->fundsLikes->sum}}</small>
                      @else
                        <small></small>
                      @endif
                  </div>
              </div>
              <div class="calendar">
                      <div class="block text-center">
                        @if ($nomination->status == 1)
                          <i class="fa fa-bell-o" aria-hidden="true"></i>
                          <small>{{$nomination->before_finish}}</small>
                       @else
                          <i class="fa fa-bell-slash-o" aria-hidden="true"></i>
                       @endif

                      </div>
                  </div>
                   <p class="text-center">
                       <a href="{{route('nomination.show', [$nomination->id])}}" class="btn btn-danger btn-lg btn-nommi" role="button"><i class="fa fa-chevron-right" aria-hidden="true"></i>&nbsp;Подробнее!</a>
                   </p>

               </div>
           </div>
       @endforeach
       <div class="clearfix"></div>

       <p class="text-left">
           <a href="{{url('/nomination')}}" class="btn btn-success btn-lg"><i class="fa fa-chevron-right" aria-hidden="true"></i>&nbsp;Все номинации</a>
       </p>



</div>


        <div class="row">
            <div class="col-lg-12">
            <h3>Реклама</h3>
          </div>
          {{--<div class="col-md-2 col-sm-3 col-xs-4">
            <a href=""><img class="img-thumbnail img-responsive" src="{{asset('/assets/img/test/index_2.jpg')}}"/></a>
          </div>
          <div class="col-md-2 col-sm-3 col-xs-4">
            <a href=""><img class="img-thumbnail img-responsive" src="{{asset('/assets/img/test/index_3.jpg')}}"/></a>
          </div>
          <div class="col-md-2 col-sm-3 col-xs-4">
            <a href=""><img class="img-thumbnail img-responsive" src="{{asset('/assets/img/test/index_2.jpg')}}"/></a>
          </div>
          <div class="col-md-2 col-sm-3 col-xs-4 hidden-xs">
            <a href=""><img class="img-thumbnail img-responsive" src="{{asset('/assets/img/test/index_3.jpg')}}"/></a>
          </div>
          <div class="col-md-2 col-sm-3 col-xs-4 hidden-sm hidden-xs">
            <a href=""><img class="img-thumbnail img-responsive" src="{{asset('/assets/img/test/index_3.jpg')}}"/></a>
          </div>
          <div class="col-md-2 col-sm-3 col-xs-4 hidden-sm hidden-xs">
            <a href=""><img class="img-thumbnail img-responsive" src="{{asset('/assets/img/test/index_2.jpg')}}"/></a>
          </div>--}}

          <div class="col-md-2 col-sm-3 col-xs-4">
            <a href="/feedback"><img class="img-thumbnail img-responsive" src="{{asset('/assets/img/test/reclama.png')}}"/></a>
          </div>
          <div class="col-md-2 col-sm-3 col-xs-4">
            <a href="/feedback"><img class="img-thumbnail img-responsive" src="{{asset('/assets/img/test/reclama.png')}}"/></a>
          </div>
          <div class="col-md-2 col-sm-3 col-xs-4">
            <a href="/feedback"><img class="img-thumbnail img-responsive" src="{{asset('/assets/img/test/reclama.png')}}"/></a>
          </div>
          <div class="col-md-2 col-sm-3 col-xs-4 hidden-xs">
            <a href="/feedback"><img class="img-thumbnail img-responsive" src="{{asset('/assets/img/test/reclama.png')}}"/></a>
          </div>
          <div class="col-md-2 col-sm-3 col-xs-4 hidden-sm hidden-xs">
            <a href="/feedback"><img class="img-thumbnail img-responsive" src="{{asset('/assets/img/test/reclama.png')}}"/></a>
          </div>
          <div class="col-md-2 col-sm-3 col-xs-4 hidden-sm hidden-xs">
            <a href="/feedback"><img class="img-thumbnail img-responsive" src="{{asset('/assets/img/test/reclama.png')}}"/></a>
          </div>
        </div>



        <div class="row">
          <div class="col-lg-12">
          <h3>Участники <small></small></h3>
        </div>
        @foreach ($competitors as $competitor)
            <div class="col-sm-3 col-xs-6">
                <div class="thumbnail index-user">
                    <div class="avatar">
                      @if($competitor->avatar=='default')
                         @php
                         $competitor->avatar= asset('assets/img/default/avatar.png');
                         @endphp
                      @endif
                        <a href="{{route('competitor.show', ['competitor' => $competitor->id])}}"><img class="img-responsive img-rounded" src="{{asset($competitor->avatar)}}" alt="{{$competitor->name}}"></a>
                    </div>

                    <div class="caption">
                        <h4 class="text-name"><a href="{{route('competitor.show', ['competitor' => $competitor->id])}}">{{$competitor->name}}</a></h4>
                        <p>

                            <a href="{{route('competitor.show', ['competitor' => $competitor->id])}}" class="color-black opacity-hide"><i class="fa fa-bar-chart" aria-hidden="true"></i>&nbsp;<small>
                                @if(!empty($competitor->ratingScore->position))
                                {{$competitor->ratingScore->position}}
                               @endif
                            </small></a>&nbsp;
                            <a href="{{route('competitor.show', ['competitor' => $competitor->id])}}#scores" class="color-black opacity-hide"><i class="fa fa-graduation-cap" aria-hidden="true"></i>&nbsp;<small>
                                @if(!empty(Nomination::avgScore($competitor->id)->first()->avgscore))
                                {{Nomination::avgScore($competitor->id)->first()->avgscore}}
                               @endif
                            </small></a>&nbsp;
                            <a href="{{route('competitor.show', ['competitor' => $competitor->id])}}#photos" class="color-red opacity-hide"><i class="fa fa-heart" aria-hidden="true"></i>&nbsp;<small>
                                {{Nomination::countLikesCompetitor($competitor->id)}}
                            </small></a>&nbsp;
                            <a href="{{route('competitor.show', ['competitor' => $competitor->id])}}#photos" class="color-black opacity-hide"><i class="fa fa-camera-retro" aria-hidden="true"></i>&nbsp;<small>
                                {{$competitor->photos->count()}}
                            </small></a>&nbsp;
                        </p>
                        <p class="text-right"><a href="{{route('competitor.show', ['competitor' => $competitor->id])}}" class="btn btn-info" role="button"><i class="fa fa-chevron-right" aria-hidden="true"></i>&nbsp;Подробнее</a></p>
                    </div>
                </div>
            </div>
        @endforeach
        <div class="clearfix"></div>


        <p class="text-left">
            <a href="{{url('/competitor')}}" class="btn btn-warning btn-lg"><i class="fa fa-chevron-right" aria-hidden="true"></i>&nbsp;Все участники</a>
        </p>
        </div>

        <div class="row">
          <div class="col-lg-12">
          <h3>Фото <small></small></h3>
        </div>
        @foreach ($photos as $photo)
            <div class="col-sm-3 col-xs-6">
                <div class="thumbnail index-photo">
                    <div class="pic">
                        <a href="{{route('photo.show', [$photo->id])}}"><img class="img-responsive img-rounded" src="{{$photo->photo}}" alt="..."></a>
                        <div class="pic-bar">
                            <h4 class="text-name"><a href="{{route('competitor.show', [$photo->getCompetitor->id])}}">{{$photo->getCompetitor->getUser->name}}</a></h4>
                            <p class="text-right">
                             <a href="" class="color-white opacity-hide-less" ><i class="fa fa-bar-chart" aria-hidden="true"></i></a>&nbsp;
                             <a href="" class="color-white opacity-hide-less" ><small>
                                 @if(!empty($photo->ratingLike->position))
                                 {{$photo->ratingLike->position}}
                                @endif
                             </small></a>&nbsp;
                             <a href="{{route('like.create', [$photo->id])}}" class="color-white opacity-hide-less" ><i class="fa fa-heart" aria-hidden="true"></i></a>&nbsp;
                             <a href="{{route('like.likes', [$photo->id])}}" class="color-white opacity-hide-less" ><small>{{$photo->likes->count()}}</small></a>&nbsp;
                            <a href="{{route('photo.show', [$photo->id])}}" class="color-white opacity-hide-less"><i class="fa fa-comments" aria-hidden="true"></i>&nbsp;<small>{{$photo->comments->count()}}</small></a>&nbsp;
                        </p>
                        </div>
                    </div>

                </div>
            </div>
        @endforeach
        <div class="clearfix"></div>

        <p class="text-left">
            <a href="{{url('/photo')}}" class="btn btn-danger btn-lg"><i class="fa fa-chevron-right" aria-hidden="true"></i>&nbsp;Все фото</a>
        </p>
      </div>


      {{--<div class="row">
        <div class="col-lg-12">
        <h3>Новости <small></small></h3>
      </div>
      @foreach ($news as $newone)
        <div class="col-sm-3 col-xs-6">
          <div class="media newslist-content">
      <h5 class="media-heading"><a href="{{route('news.show', [$newone->id])}}">{{$newone->header}}</a></h5>
      <a href="{{route('news.show', [$newone->id])}}">
          <img class="media-object img-thumbnail" src="{{$newone->pic}}" alt="{{$newone->header}}">
      </a>
      <div class="media-body">
          <p class="text-muted pull-left"><small>{{$newone->author}}</small></p>
          <p class="text-muted pull-right"><small>{{ date('d.m.Y', strtotime($newone->publish_at)) }}</small></p>
          <div class="clearfix"></div>
          <p>
          {!!$newone->introtext!!}
          </p>
      </div>

      <p class="text-right">
          <a href="{{route('news.show', [$newone->id])}}" class="btn btn-lg btn-warning"><i class="fa fa-chevron-right" aria-hidden="true"></i>&nbsp;Подробнее</a>
      </p>
  </div>
</div>
      @endforeach
    </div>--}}



@endsection