routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
 */

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/', ['uses' => 'IndexController@index', 'as' => 'index']);

Auth::routes();

//Подтверждение регистрации
Route::get('/confirm/{id}/{code}', ['uses' => 'Auth\RegisterController@confirmRegistration', 'as' => 'confirm']);

//Аутентификация, переопределенные роуты
// Вызов страницы регистрации пользователя
Route::get('/register', ['uses' => 'Auth\RegisterController@showRegistrationForm', 'as' => 'register']);

// Вызов формы ввода e-mail для сброса пароля
Route::get('/password/reset', ['uses' => 'Auth\ForgotPasswordController@showLinkRequestForm', 'as' => 'password.reset']);

// Вызов формы ввода нового пароля при сбросе
Route::get('/password/reset/{token}', ['uses' => 'Auth\ResetPasswordController@showResetForm', 'as' => 'password.token']);

// При запрещенном к просмотру разделе
Route::get('noaccess', ['uses' => 'Auth\NoaccessController@noaccess', 'as' => 'noaccess']);

Route::get('/home', 'HomeController@index');

//Пользователи
Route::resource('users', 'UserController');
Route::post('users/search', ['uses' => 'UserController@search', 'as' => 'users.search']);
Route::post('users/{user}/password', ['uses' => 'UserController@changePassword', 'as' => 'users.password']);
Route::get('users/{users}/newscomments', ['uses' => 'UserController@newsComments', 'as' => 'users.newscomments']);
Route::get('users/{users}/nominations', ['uses' => 'UserController@getUserNominations', 'as' => 'users.nominations']);
Route::get('users/comments/{user}', ['uses' => 'UserController@comments', 'as' => 'users.comments']);

// Обратная связь

Route::resource('feedback', 'FeedbackController');
Route::post('feedback/send', ['uses' => 'FeedbackController@send', 'as' => 'feedback.send']);

//Новости

Route::resource('news', 'NewsController');
Route::post('news/{news}/{user}/addcomment', ['uses' => 'NewsController@addComment', 'as' => 'news.addcomment']);

//Номинация

Route::resource('nomination', 'NominationController');
Route::get('nomination/{nomination}/competitors', ['uses' => 'NominationController@getCompetitors', 'as' => 'nomination.competitors']);
Route::get('nomination/{nomination}/description', ['uses' => 'NominationController@showDescription', 'as' => 'nomination.description']);
Route::get('nomination/{nomination}/photos', ['uses' => 'NominationController@photos', 'as' => 'nomination.photos']);
Route::get('nomination/{nomination}/{agree?}', ['uses' => 'NominationController@show', 'as' => 'nomination.show']);

// Competitors

Route::resource('competitor', 'CompetitorController');
Route::post('competitor/{nomination}/create', ['uses' => 'CompetitorController@create', 'as' => 'competitor.create']);
//Route::post('competitor/search', ['uses' => 'CompetitorController@search', 'as' => 'competitor.search']);
Route::post('competitor', ['uses' => 'CompetitorController@index', 'as' => 'competitor.search']);
Route::get('champion', ['uses' => 'CompetitorController@champions', 'as' => 'champion']);


//Фотогалерея

Route::resource('photo', 'PhotoController');
Route::post('photo/{competitor}/{nomination}', ['uses' => 'PhotoController@store', 'as' => 'photo.store']); // основное фото
Route::post('photo/{competitor}/{nomination}/addition', ['uses' => 'PhotoController@storeAddition', 'as' => 'photo.store.addition']); // дополнительное фото
Route::get('photo/confirm/addition/{competitor}/{photo}', ['uses' => 'PhotoController@confirmAddition', 'as' => 'photo.confirm.addition']); // дополнительное фото, подтверждение публикации
Route::post('photo/search', ['uses' => 'PhotoController@index', 'as' => 'photo.search']);

//Комментарии

Route::resource('comment', 'CommentController');
Route::post('comment/add/news/{instance}/{user}', ['uses' => 'CommentController@storeCommentNews', 'as' => 'comment.store.news']);
Route::post('comment/add/competitor/{instance}/{user}', ['uses' => 'CommentController@storeCommentCompetitor', 'as' => 'comment.store.competitor']);
Route::post('comment/add/photo/{instance}/{user}', ['uses' => 'CommentController@storeCommentPhoto', 'as' => 'comment.store.photo']);
Route::post('comment/add/nomination/{instance}/{user}', ['uses' => 'CommentController@storeCommentNomination', 'as' => 'comment.store.nomination']);
Route::get('comment/info/{comment}/{user}', ['uses' => 'CommentController@infoModerator', 'as' => 'comment.info.moderator']);

// Лайки

Route::resource('like', 'LikeController');
Route::get('likes/buy/{user}', ['uses' => 'LikeController@buy', 'as' => 'like.buy']);
Route::post('likes/add', ['uses' => 'LikeController@add', 'as' => 'like.add']);
Route::get('like/create/{photo}', ['uses' => 'LikeController@create', 'as' => 'like.create']);
Route::get('likes/{photo}', ['uses' => 'LikeController@likes', 'as' => 'like.likes']);

// Судейство

Route::resource('referee', 'RefereeController');
Route::get('referee/score/{competitor}', ['uses' => 'RefereeController@score', 'as' => 'referee.score']);
Route::post('referee/score/{competitor}', ['uses' => 'RefereeController@storeScore', 'as' => 'referee.score.store']);

// Призовой фонд

Route::resource('fund', 'FundController');

// Рейтинг

Route::resource('rating', 'RatingController');
Route::get('rating/score/{nomination}', ['uses' => 'RatingController@showRatingScore', 'as' => 'rating.score']);
Route::get('rating/like/{nomination}', ['uses' => 'RatingController@showRatingLike', 'as' => 'rating.like']);

// Обработка персональных данных

Route::get('/personal-data', ['uses' => 'ContentController@showPersonalData', 'as' => 'personal_data.index']);

// Подробно о сайте

Route::get('/site-description', ['uses' => 'ContentController@showSiteDescription', 'as' => 'site_description']);

// Пользовательское соглашение

Route::get('/user-agreement', ['uses' => 'ContentController@showUserAgreement', 'as' => 'user_agreement']);

// Справка

Route::get('/help', ['uses' => 'ContentController@showHelp', 'as' => 'help']);

//Cookies

Route::post('/cookie/index/informer', ['uses' => 'CookieController@setCookieIndexInformer', 'as' => 'cookie.index.informer']);
Route::post('/cookie/nomination/informer', ['uses' => 'CookieController@setCookieNominationInformer', 'as' => 'cookie.nomination.informer']);
Route::post('/cookie/photos/informer', ['uses' => 'CookieController@setCookiePhotosInformer', 'as' => 'cookie.photos.informer']);
Route::post('/cookie/competitors/informer', ['uses' => 'CookieController@setCookieCompetitorsInformer', 'as' => 'cookie.competitors.informer']);
Route::post('/cookie/competitor/edit/informer', ['uses' => 'CookieController@setCookieCompetitorEditInformer', 'as' => 'cookie.competitor.edit.informer']);
Route::post('/cookie/competitor/informer', ['uses' => 'CookieController@setCookieCompetitorInformer', 'as' => 'cookie.competitor.informer']);
Route::post('/cookie/funds/informer', ['uses' => 'CookieController@setCookieFundsInformer', 'as' => 'cookie.funds.informer']);
Route::post('/cookie/likebuy/informer', ['uses' => 'CookieController@setCookieLikebuyInformer', 'as' => 'cookie.likebuy.informer']);
Route::post('/cookie/photo/informer', ['uses' => 'CookieController@setCookiePhotoInformer', 'as' => 'cookie.photo.informer']);
Route::post('/cookie/ratings/informer', ['uses' => 'CookieController@setCookieRatingsInformer', 'as' => 'cookie.ratings.informer']);
Route::post('/cookie/rating/likes/informer', ['uses' => 'CookieController@setCookieRatingLikesInformer', 'as' => 'cookie.rating.likes.informer']);
Route::post('/cookie/rating/scores/informer', ['uses' => 'CookieController@setCookieRatingScoresInformer', 'as' => 'cookie.rating.scores.informer']);
Route::post('/cookie/users/informer', ['uses' => 'CookieController@setCookieUsersInformer', 'as' => 'cookie.users.informer']);
Route::post('/cookie/user/edit/informer', ['uses' => 'CookieController@setCookieUserEditInformer', 'as' => 'cookie.user.edit.informer']);
Route::post('/cookie/user/informer', ['uses' => 'CookieController@setCookieUserInformer', 'as' => 'cookie.user.informer']);

//Платежные системы

//Форма оплаты за участие в номинации
Route::get('/payment/yandexmoney/{nomination}', ['uses' => 'Payment\YandexMoneyController@showFormNomination', 'as' => 'payment.yandexmoney.nomination']);
//Страница перехода с платежной системы при оплате участия в номинации
//Route::get('/payment/yandexmoney/recive/nomination/{nomination}', ['uses' => 'Payment\YandexMoneyController@recivePaymentNomination', 'as' => 'payment.yandexmoney.recive.nomination']);
//Форма оплаты загрузки дополнительных фото
Route::get('/payment/yandexmoney/{nomination}/additionalphoto', ['uses' => 'Payment\YandexMoneyController@showFormAdditionalPhoto', 'as' => 'payment.yandexmoney.additionalphoto']);


// Верстка

Route::group(['middleware' => 'makeup'], function () {

    Route::get('/template', function () {
        return view('makeup.template');
    });

    Route::get('/makeup/feedback', function () {
        return view('makeup.feedback');
    });

    Route::get('/makeup/nomination-index', function () {
        return view('makeup.nomination-index');
    });

    Route::get('/makeup/nomination-show', function () {
        return view('makeup.nomination-show');
    });

// Верстка jasny

    Route::get('/makeup/jasny', function () {
        return view('makeup.jasny');
    });

    Route::get('/makeup/main', function () {
        return view('makeup.main');
    });

    Route::get('/makeup/index', function () {
        return view('makeup.index');
    });

    Route::get('/makeup/text', function () {
        return view('makeup.text');
    });

    Route::get('/makeup/content', function () {

app/Competitor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Competitor extends Model
{

    use \KodiComponents\Support\Upload;

    protected $casts = [
        'avatar' => 'image', // or file | upload
    ];

    /**
     * Получение пользователя по участнику номинации
     */
    public function getUser()
    {
        return $this->belongsTo('App\User', 'user_id');
    }

    /**
     * Получение номинации по участнику
     */
    public function getNomination()
    {
        return $this->belongsTo('App\Nomination', 'nomination_id');
    }

    /**
     * Получение фото по участнику
     */
    public function getPhoto()
    {
        return $this->hasMany('App\Photo');
    }


    /**
     * Получение одобренных фото по участнику
     */
    public function photos()
    {
        return $this->hasMany('App\Photo')->where('photo_status_id','=', 2);
    }

    /**
     * Получить все комментарии участника
     */
    public function comments()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }

    /**
     * Получение просмотров судей
     */
    public function review() {
       return $this->hasMany('App\Review');
    }


    /**
     * Получение судейских оценок
     */
    public function score() {
       return $this->hasMany('App\Score');
    }



    /**
     * Получение рейтинга оценок
     */
    public function ratingScore() {
       return $this->hasOne('App\RatingScore');
    }




}

resources/views/competitor/agreement.blade.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

resources/views/competitor/all_competitors.blade.php
@extends('competitor.index')
@section('breadcrumbs')
{!! Breadcrumbs::render('competitor.all') !!}
@endsection
@section('competitors_title')
@if(!isset($nomination_current))
Участники всех номинаций <small></small>
@else
Участники номинации "{{strip_tags($nomination_current->name)}}" <small>Результаты поиска</small>
@endif
@endsection
@section('subheader')
Все участники во всех номинациях
@endsection
@section('competitors_search')

<div class="col-lg-12">
    <form class="form-inline" role="search" method="POST" action="{{ route('competitor.search') }}">
        {{ csrf_field() }}
        <div class="form-group">
            <select name="nomination" class="form-control">
                <option value="">Номинация</option>
                @foreach ($nominations as $nomination)
                <option value="{{$nomination->id}}">{{strip_tags($nomination->name)}}</option>
                @endforeach
            </select>

        </div>
        <div class="form-group">
            <select name="sex" class="form-control">
                <option value="мужской" >мужской</option>
                <option value="женский" >женский</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Найти</button>
    </form>
</div>


@endsection

resources/views/competitor/champions.blade.php
@extends('layouts.bibikini')
@section('breadcrumbs')
{!! Breadcrumbs::render('champion') !!}
@endsection
@section('header')
        <h1>Чемпионы</h1>
@endsection
@section('content')
  <div class="row">
    @foreach ($nominations as $nomination)
          <div class="col-lg-12">
              <h2><a href="{{route('nomination.show', [$nomination->id])}}">{!! $nomination->name !!}</a></h2>

              @php
              $champions = $nomination->ratingScores->slice(0, 3);
              $first_place = $champions[0];
              $second_place = $champions[1];
              $third_place = $champions[2];
              $champions = [$second_place, $first_place, $third_place]
              @endphp

            <div class="rating-block">
                @foreach ($champions  as $ratingScore)
                    <div class="block">
                      @if($loop->iteration == 1)
                        <h4 class="text-center text-primary">&#8545; место</h4>
                      @elseif($loop->iteration == 2)
                       <h4 class="text-center text-warning">&#8544; место</h4>
                      @elseif($loop->iteration == 3)
                        <h4 class="text-center text-success">&#8546; место</h4>
                     @endif
                        <div class="thumbnail">
                            <a href="{{route('competitor.show', [$ratingScore->competitor_id])}}"><img src="{{asset($ratingScore->competitor->avatar)}}" /></a>
                        </div>
                        <p class="prize text-center">
                            <i class="fa fa-graduation-cap" aria-hidden="true"></i><small><a href="{{route('competitor.show', [$ratingScore->competitor_id])}}#scores">{{$ratingScore->avscore}}</a></small>
                       </p>
                        <a href="{{route('rating.score', [$nomination->id])}}"
                          @if($loop->iteration == 1)
                            class="lenta prize second"
                          @elseif($loop->iteration == 2)
                            class="lenta prize first"
                          @elseif($loop->iteration == 3)
                            class="lenta prize third"
                         @endif
                          style="height: {{Nomination::ratingLentaHeight($ratingScore->avscore, 2, 'px')}};"></a>
                    </div>
                @endforeach
                </div>

          </div>
   @endforeach
  </div>
@endsection

resources/views/competitor/edit.blade.php
@extends('layouts.bibikini')
@section('breadcrumbs')
{!! Breadcrumbs::render('competitor.edit', $competitor->id) !!}
@endsection
@section('header')
  <h1>{{$competitor->getUser->name}}
    @if($competitor->is_champion == 1)
      <small class="text-warning">Призёр номинации "{{strip_tags($competitor->getNomination->name)}}", занял {{$competitor->prize_place}} место</small>
    @else
    <small>Участник номинации "{{strip_tags($competitor->getNomination->name)}}"</small>
   @endif
  </h1>
@endsection
@section('informer')
  @if (!Cookie::get('informer-competitor-edit') )
    @include('widget.informer',['contents' => $contents, 'content_key'=>'competitor_edit', 'cookie_url'=>'/cookie/competitor/edit/informer'])
  @endif
@endsection
@section('content')
@include('modals.upload_photo')




    <div class="row">
        <div class="col-sm-6">
          @if($competitor->avatar=='default')
             @php
             $competitor->avatar= asset('assets/img/default/avatar.png');
             @endphp
          @endif
            <a href="{{asset($competitor->avatar)}}" data-toggle="lightbox" data-title="{{$competitor->getUser->name}}" data-footer="{{$competitor->getUser->name}}">
                <img src="{{asset($competitor->avatar)}}" class="img-responsive img-thumbnail pull-left img-content img-left" alt="{{$competitor->getUser->name}}">
            </a>
        </div>
        <div class="col-sm-6">
            <h3>Информация</h3>
            <div class="table-responsive">
                <table class="table">
                    <tr>
                        <td>
                            Имя
                        </td>
                        <td>
                            {{$competitor->getUser->name}}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Хэштег участника
                        </td>
                        <td>
                            {{$competitor->hashtag}}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Хэштег пользователя
                        </td>
                        <td>
                            {{$competitor->getUser->hashtag}}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Пол
                        </td>
                        <td>
                            {{$competitor->getUser->sex}}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Пользователь
                        </td>
                        <td>
                            <a href="{{route('users.show', [$competitor->getUser->id])}}">{{$competitor->getUser->name}}</a>
                        </td>
                    </tr>
                </table>
            </div>
            <h3>О себе</h3>
            <p>{{$competitor->about}}</p>

        </div>
    </div>
    @if($competitor->is_champion == 1)
      <br><br>
      <div class="row">
        <div class="col-lg-12">
          <h3>Чемпион <small>Подтверждения получения приза и т п</small></h3>
          {!! $competitor->champion_description !!}
        </div>
        </div>
    @endif
    <br><br>
    <div class="row">
        <div class="col-lg-12">
            <button type="button" class="form-control btn-primary" data-toggle="collapse" data-target="#editdata">
                Редактировать информацию, изменить аватар <i class="fa fa-chevron-down" aria-hidden="true"></i>
            </button>

            <div id="editdata" class="collapse">
                <form class="form-horizontal incollapse" role="form" method="POST" action="{{ url('competitor/'.$competitor->id) }}" enctype = "multipart/form-data">
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}
                    <div class="form-group">
                        <label for="about" class="col-sm-2 control-label">О себе</label>
                        <div class="col-sm-7 col-sm-offset-1">
                            <textarea class="form-control" rows="5" name="about">{{$competitor->about}}</textarea>
                            <p class="help-block text-danger">{!! $errors->first('about') !!}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="avatar" class="col-sm-2 control-label"></label>
                        <div class="col-sm-10">
                            <input type="file" class="form-control btn-primary" name="avatar" title="Загрузить аватар">
                            <p class="help-block text-danger">{!! $errors->first('avatar') !!}</p>
                            <p  class="text-danger"><small>Допускается загрузка изображений форматов png, jpg, jpeg, gif размером не более 1МБ.</small></p>
                        </div>
                    </div>

                    <div class="form-group">
                      <div class="col-sm-offset-2 col-sm-5 col-xs-6">
                          <a href="{{Request::url()}}" class="btn btn-danger">Отменить</a>
                      </div>
                        <div class="col-sm-5 col-xs-6">
                            <button type="submit" class="btn btn-success pull-right">Сохранить</button>
                        </div>

                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="row">
      <div class="col-lg-12">
        <a name="photos"></a>
      <h3>Фотогалерея <small>Для загрузки фото нажмите на "плюс"</small></h3>
    </div>
    @foreach ($competitor->getPhoto as $photo)
     @if($photo->photo_status_id == 1)

            <div class="col-md-2 col-xs-4">
        <div class="thumbnail photo">
            <div class="pic mini download">
                <a href="{{route('photo.show', [$photo->id])}}"><img class="img-responsive img-rounded" src="{{$photo->photo}}" alt="..."></a>
                <div class="pic-bar">
                    <p class="text-center">
                        Проверка
                    </p>
                </div>
            </div>

        </div>
    </div>
  @elseif($photo->photo_status_id == 4)

           <div class="col-md-2 col-xs-4">
       <div class="thumbnail photo">
           <div class="pic mini download">
               <a href="{{route('photo.show', [$photo->id])}}"><img class="img-responsive img-rounded" src="{{$photo->photo}}" alt="..."></a>
               <div class="pic-bar">
                   <p class="text-center">
                       Дополнительное
                   </p>
               </div>
           </div>

       </div>
   </div>
        @elseif($photo->photo_status_id == 2)
            <div class="col-md-2 col-xs-4">
                <div class="thumbnail photo">
                    <div class="pic mini">
                        <a href="{{route('photo.show', [$photo->id])}}"><img class="img-responsive img-rounded" src="{{$photo->photo}}" alt="..."></a>
                        <div class="pic-bar">

                            <p class="text-right">
                                <a href="" class="color-black opacity-hide-less" ><i class="fa fa-bar-chart" aria-hidden="true"></i></a>&nbsp;
                                <a href="" class="color-black opacity-hide-less" ><small>
                                    @if(!empty($photo->ratingLike->position))
                                    {{$photo->ratingLike->position}}
                                   @endif
                                </small></a>&nbsp;
                             <a href="{{route('like.create', [$photo->id])}}" class="color-red opacity-hide-less" ><i class="fa fa-heart" aria-hidden="true"></i></a>&nbsp;
                             <a href="{{route('like.likes', [$photo->id])}}" class="color-red opacity-hide-less" ><small>{{$photo->likes->count()}}</small></a>&nbsp;
                            <a href="{{route('photo.show', [$photo->id])}}" class="color-black opacity-hide-less"><i class="fa fa-comments" aria-hidden="true"></i>&nbsp;<small>{{$photo->comments->count()}}</small></a>&nbsp;
                        </p>
                        </div>
                    </div>

                </div>
            </div>

        @else
            <div class="col-md-2 col-xs-4">
        <div class="thumbnail photo">
            <div class="pic mini rejected">
                <a href="{{route('photo.show', [$photo->id])}}"><img class="img-responsive img-rounded" src="{{$photo->photo}}" alt="..."></a>
                <div class="pic-bar">
                    <p class="text-center">
                        Отклонена
                    </p>
                </div>
            </div>

        </div>
    </div>

    @endif
    @endforeach
    <a name="uploadPhoto"></a>
    <div class="col-md-2 col-xs-3">
        <div class="photo">
            <div class="pic mini">
                <a class="pic-add" href="" data-toggle="modal" data-target="#modalUploadPhoto"><i class="fa fa-plus-square-o fa-5x" aria-hidden="true"></i></a>

            </div>

        </div>
    </div>
      </div>

    <div class='row'>
     <div class="col-lg-12">
      <a name="scores"></a>
      <h3>Оценки <small>Судьи должны оценивать участников! При отсутствии оценок обращайтесь к администрации.</small></h3>

      @include('widget.table_score_agr')

    </div>
    </div>

    <div class="row">

    <div class="col-lg-12">
    @include('comment.comments_block', ['url'=>'comment.store.competitor', 'instance' => $competitor->id, 'comments' => $competitor->comments])
    </div>
    </div>

@endsection

resources/views/competitor/nomination_competitors.blade.php
@extends('competitor.index')
@section('breadcrumbs')
{!! Breadcrumbs::render('competitor.index', $nomination->id) !!}
@endsection
@section('competitors_title')
Участники номинации "{{strip_tags($nomination->name)}}" <small>{{$nomination->type}}</small>
@endsection
@section('subheader')
Участники номинации
@endsection
@section('lead_introtext')
{{$nomination->introtext}} <br>
Перед тем, как участвовать, обязательно прочитайте <a href="ЗДЕСЬ ССЫЛКА НА ПРАВИЛА">правила</a>!
@endsection
@section('competitor_name')

@endsection

resources/views/competitor/show.blade.php
@extends('layouts.bibikini')
@section('breadcrumbs')
{!! Breadcrumbs::render('competitor.show', $competitor->id) !!}
@endsection
@section('header')
        <h1>{{$competitor->getUser->name}}
          @if($competitor->is_champion == 1)
            <small class="text-warning">Призёр номинации "{{strip_tags($competitor->getNomination->name)}}", занял {{$competitor->prize_place}} место</small>
          @else
          <small>Участник номинации "{{strip_tags($competitor->getNomination->name)}}"</small>
         @endif
        </h1>
@endsection
@section('informer')
  @if (!Cookie::get('informer-competitor') )
    @include('widget.informer',['contents' => $contents, 'content_key'=>'competitor_profile', 'cookie_url'=>'/cookie/competitor/informer'])
  @endif
@endsection
@section('content')
  <div class="row">
        <div class="col-sm-6">
          @if($competitor->avatar=='default')
             @php
             $competitor->avatar= asset('assets/img/default/avatar.png');
             @endphp
          @endif
            <a href="{{asset($competitor->avatar)}}" data-toggle="lightbox" data-title="{{$competitor->getUser->name}}" data-footer="{{$competitor->getUser->name}}">
                <img src="{{asset($competitor->avatar)}}" class="img-responsive img-thumbnail pull-left img-content img-left" alt="{{$competitor->getUser->name}}">
            </a>
        </div>
        <div class="col-sm-6">
            <h3>Информация</h3>
            <div class="table-responsive">
                <table class="table">
                    <tr>
                        <td>
                            Имя
                        </td>
                        <td>
                            {{$competitor->getUser->name}}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Хэштег участника
                        </td>
                        <td>
                            {{$competitor->hashtag}}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Хэштег пользователя
                        </td>
                        <td>
                            {{$competitor->getUser->hashtag}}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Пол
                        </td>
                        <td>
                            {{$competitor->getUser->sex}}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Пользователь
                        </td>
                        <td>
                            <a href="{{route('users.show', [$competitor->getUser->id])}}">{{$competitor->getUser->name}}</a>
                        </td>
                    </tr>
                </table>
            </div>
            <h3>О себе</h3>
            <p>{{$competitor->about}}</p>
        </div>
    </div>
    @if($competitor->is_champion == 1)
      <div class="row">
        <div class="col-lg-12">
          <h3>Чемпион <small>Подтверждения получения приза и т п</small></h3>
          {!! $competitor->champion_description !!}
        </div>
        </div>
    @endif


    <div class="row">
      <div class="col-lg-12">
        <a name="photos"></a>
      <h3>Фотогалерея <small></small></h3>
    </div>
    @foreach ($competitor->getPhoto as $photo)
    <div class="col-md-2 col-xs-3">
        <div class="thumbnail photo">
            <div class="pic mini">
                <a href="{{route('photo.show', [$photo->id])}}"><img class="img-responsive img-rounded" src="{{$photo->photo}}" alt="..."></a>
                <div class="pic-bar">

                    <p class="text-right">
                        <a href="" class="color-black opacity-hide-less" ><i class="fa fa-bar-chart" aria-hidden="true"></i></a>&nbsp;
                        <a href="" class="color-black opacity-hide-less" ><small>
                            @if(!empty($photo->ratingLike->position))
                            {{$photo->ratingLike->position}}
                           @endif
                        </small></a>&nbsp;
                     <a href="{{route('like.create', [$photo->id])}}" class="color-red opacity-hide-less" ><i class="fa fa-heart" aria-hidden="true"></i></a>&nbsp;
                     <a href="{{route('like.likes', [$photo->id])}}" class="color-red opacity-hide-less" ><small>{{$photo->likes->count()}}</small></a>&nbsp;
                    <a href="{{route('photo.show', [$photo->id])}}" class="color-black opacity-hide-less"><i class="fa fa-comments" aria-hidden="true"></i>&nbsp;<small>{{$photo->comments->count()}}</small></a>&nbsp;
                </p>
                </div>
            </div>

        </div>
    </div>
    @endforeach
      </div>


    <div class='row'>
     <div class="col-lg-12">
      <a name="scores"></a>
      <h3>Оценки <small>Судьи должны оценивать участников! При отсутствии оценок обращайтесь к администрации.</small></h3>

      @include('widget.table_score_agr')

    </div>
    </div>


    <div class="row">

    <div class="col-lg-12">
    @include('comment.comments_block', ['url'=>'comment.store.competitor', 'instance' => $competitor->id, 'comments' => $competitor->comments])
    </div>
    </div>
@endsection