routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
 */

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/', ['uses' => 'IndexController@index', 'as' => 'index']);

Auth::routes();

//Подтверждение регистрации
Route::get('/confirm/{id}/{code}', ['uses' => 'Auth\RegisterController@confirmRegistration', 'as' => 'confirm']);

//Аутентификация, переопределенные роуты
// Вызов страницы регистрации пользователя
Route::get('/register', ['uses' => 'Auth\RegisterController@showRegistrationForm', 'as' => 'register']);

// Вызов формы ввода e-mail для сброса пароля
Route::get('/password/reset', ['uses' => 'Auth\ForgotPasswordController@showLinkRequestForm', 'as' => 'password.reset']);

// Вызов формы ввода нового пароля при сбросе
Route::get('/password/reset/{token}', ['uses' => 'Auth\ResetPasswordController@showResetForm', 'as' => 'password.token']);

// При запрещенном к просмотру разделе
Route::get('noaccess', ['uses' => 'Auth\NoaccessController@noaccess', 'as' => 'noaccess']);

Route::get('/home', 'HomeController@index');

//Пользователи
Route::resource('users', 'UserController');
Route::post('users/search', ['uses' => 'UserController@search', 'as' => 'users.search']);
Route::post('users/{user}/password', ['uses' => 'UserController@changePassword', 'as' => 'users.password']);
Route::get('users/{users}/newscomments', ['uses' => 'UserController@newsComments', 'as' => 'users.newscomments']);
Route::get('users/{users}/nominations', ['uses' => 'UserController@getUserNominations', 'as' => 'users.nominations']);
Route::get('users/comments/{user}', ['uses' => 'UserController@comments', 'as' => 'users.comments']);

// Обратная связь

Route::resource('feedback', 'FeedbackController');
Route::post('feedback/send', ['uses' => 'FeedbackController@send', 'as' => 'feedback.send']);

//Новости

Route::resource('news', 'NewsController');
Route::post('news/{news}/{user}/addcomment', ['uses' => 'NewsController@addComment', 'as' => 'news.addcomment']);

//Номинация

Route::resource('nomination', 'NominationController');
Route::get('nomination/{nomination}/competitors', ['uses' => 'NominationController@getCompetitors', 'as' => 'nomination.competitors']);
Route::get('nomination/{nomination}/description', ['uses' => 'NominationController@showDescription', 'as' => 'nomination.description']);
Route::get('nomination/{nomination}/photos', ['uses' => 'NominationController@photos', 'as' => 'nomination.photos']);
Route::get('nomination/{nomination}/{agree?}', ['uses' => 'NominationController@show', 'as' => 'nomination.show']);

// Competitors

Route::resource('competitor', 'CompetitorController');
Route::post('competitor/{nomination}/create', ['uses' => 'CompetitorController@create', 'as' => 'competitor.create']);
//Route::post('competitor/search', ['uses' => 'CompetitorController@search', 'as' => 'competitor.search']);
Route::post('competitor', ['uses' => 'CompetitorController@index', 'as' => 'competitor.search']);
Route::get('champion', ['uses' => 'CompetitorController@champions', 'as' => 'champion']);


//Фотогалерея

Route::resource('photo', 'PhotoController');
Route::post('photo/{competitor}/{nomination}', ['uses' => 'PhotoController@store', 'as' => 'photo.store']); // основное фото
Route::post('photo/{competitor}/{nomination}/addition', ['uses' => 'PhotoController@storeAddition', 'as' => 'photo.store.addition']); // дополнительное фото
Route::get('photo/confirm/addition/{competitor}/{photo}', ['uses' => 'PhotoController@confirmAddition', 'as' => 'photo.confirm.addition']); // дополнительное фото, подтверждение публикации
Route::post('photo/search', ['uses' => 'PhotoController@index', 'as' => 'photo.search']);

//Комментарии

Route::resource('comment', 'CommentController');
Route::post('comment/add/news/{instance}/{user}', ['uses' => 'CommentController@storeCommentNews', 'as' => 'comment.store.news']);
Route::post('comment/add/competitor/{instance}/{user}', ['uses' => 'CommentController@storeCommentCompetitor', 'as' => 'comment.store.competitor']);
Route::post('comment/add/photo/{instance}/{user}', ['uses' => 'CommentController@storeCommentPhoto', 'as' => 'comment.store.photo']);
Route::post('comment/add/nomination/{instance}/{user}', ['uses' => 'CommentController@storeCommentNomination', 'as' => 'comment.store.nomination']);
Route::get('comment/info/{comment}/{user}', ['uses' => 'CommentController@infoModerator', 'as' => 'comment.info.moderator']);

// Лайки

Route::resource('like', 'LikeController');
Route::get('likes/buy/{user}', ['uses' => 'LikeController@buy', 'as' => 'like.buy']);
Route::post('likes/add', ['uses' => 'LikeController@add', 'as' => 'like.add']);
Route::get('like/create/{photo}', ['uses' => 'LikeController@create', 'as' => 'like.create']);
Route::get('likes/{photo}', ['uses' => 'LikeController@likes', 'as' => 'like.likes']);

// Судейство

Route::resource('referee', 'RefereeController');
Route::get('referee/score/{competitor}', ['uses' => 'RefereeController@score', 'as' => 'referee.score']);
Route::post('referee/score/{competitor}', ['uses' => 'RefereeController@storeScore', 'as' => 'referee.score.store']);

// Призовой фонд

Route::resource('fund', 'FundController');

// Рейтинг

Route::resource('rating', 'RatingController');
Route::get('rating/score/{nomination}', ['uses' => 'RatingController@showRatingScore', 'as' => 'rating.score']);
Route::get('rating/like/{nomination}', ['uses' => 'RatingController@showRatingLike', 'as' => 'rating.like']);

// Обработка персональных данных

Route::get('/personal-data', ['uses' => 'ContentController@showPersonalData', 'as' => 'personal_data.index']);

// Подробно о сайте

Route::get('/site-description', ['uses' => 'ContentController@showSiteDescription', 'as' => 'site_description']);

// Пользовательское соглашение

Route::get('/user-agreement', ['uses' => 'ContentController@showUserAgreement', 'as' => 'user_agreement']);

// Справка

Route::get('/help', ['uses' => 'ContentController@showHelp', 'as' => 'help']);

//Cookies

Route::post('/cookie/index/informer', ['uses' => 'CookieController@setCookieIndexInformer', 'as' => 'cookie.index.informer']);
Route::post('/cookie/nomination/informer', ['uses' => 'CookieController@setCookieNominationInformer', 'as' => 'cookie.nomination.informer']);
Route::post('/cookie/photos/informer', ['uses' => 'CookieController@setCookiePhotosInformer', 'as' => 'cookie.photos.informer']);
Route::post('/cookie/competitors/informer', ['uses' => 'CookieController@setCookieCompetitorsInformer', 'as' => 'cookie.competitors.informer']);
Route::post('/cookie/competitor/edit/informer', ['uses' => 'CookieController@setCookieCompetitorEditInformer', 'as' => 'cookie.competitor.edit.informer']);
Route::post('/cookie/competitor/informer', ['uses' => 'CookieController@setCookieCompetitorInformer', 'as' => 'cookie.competitor.informer']);
Route::post('/cookie/funds/informer', ['uses' => 'CookieController@setCookieFundsInformer', 'as' => 'cookie.funds.informer']);
Route::post('/cookie/likebuy/informer', ['uses' => 'CookieController@setCookieLikebuyInformer', 'as' => 'cookie.likebuy.informer']);
Route::post('/cookie/photo/informer', ['uses' => 'CookieController@setCookiePhotoInformer', 'as' => 'cookie.photo.informer']);
Route::post('/cookie/ratings/informer', ['uses' => 'CookieController@setCookieRatingsInformer', 'as' => 'cookie.ratings.informer']);
Route::post('/cookie/rating/likes/informer', ['uses' => 'CookieController@setCookieRatingLikesInformer', 'as' => 'cookie.rating.likes.informer']);
Route::post('/cookie/rating/scores/informer', ['uses' => 'CookieController@setCookieRatingScoresInformer', 'as' => 'cookie.rating.scores.informer']);
Route::post('/cookie/users/informer', ['uses' => 'CookieController@setCookieUsersInformer', 'as' => 'cookie.users.informer']);
Route::post('/cookie/user/edit/informer', ['uses' => 'CookieController@setCookieUserEditInformer', 'as' => 'cookie.user.edit.informer']);
Route::post('/cookie/user/informer', ['uses' => 'CookieController@setCookieUserInformer', 'as' => 'cookie.user.informer']);

//Платежные системы

//Форма оплаты за участие в номинации
Route::get('/payment/yandexmoney/{nomination}', ['uses' => 'Payment\YandexMoneyController@showFormNomination', 'as' => 'payment.yandexmoney.nomination']);
//Страница перехода с платежной системы при оплате участия в номинации
//Route::get('/payment/yandexmoney/recive/nomination/{nomination}', ['uses' => 'Payment\YandexMoneyController@recivePaymentNomination', 'as' => 'payment.yandexmoney.recive.nomination']);
//Форма оплаты загрузки дополнительных фото
Route::get('/payment/yandexmoney/{nomination}/additionalphoto', ['uses' => 'Payment\YandexMoneyController@showFormAdditionalPhoto', 'as' => 'payment.yandexmoney.additionalphoto']);


// Верстка

Route::group(['middleware' => 'makeup'], function () {

    Route::get('/template', function () {
        return view('makeup.template');
    });

    Route::get('/makeup/feedback', function () {
        return view('makeup.feedback');
    });

    Route::get('/makeup/nomination-index', function () {
        return view('makeup.nomination-index');
    });

    Route::get('/makeup/nomination-show', function () {
        return view('makeup.nomination-show');
    });

// Верстка jasny

    Route::get('/makeup/jasny', function () {
        return view('makeup.jasny');
    });

    Route::get('/makeup/main', function () {
        return view('makeup.main');
    });

    Route::get('/makeup/index', function () {
        return view('makeup.index');
    });

    Route::get('/makeup/text', function () {
        return view('makeup.text');
    });

    Route::get('/makeup/content', function () {

resources/views/widget/blue_bar.blade.php
<div class="container-fluid">


<div class="row visible-xs visible-sm visible-md">
    <div class="link-mobile">
      <div class="btn-group">
        @if (Auth::user())
          @if(Auth::user()->avatar=='default')
             @php
             Auth::user()->avatar= asset('assets/img/default/avatar.png');
             @endphp
          @endif
    <button type="button"  data-toggle="dropdown">
      <img style="max-height: 46px; display: inline-block; margin-bottom: 0;" src="{{asset(Auth::user()->avatar)}}" alt="{{Auth::user()->name}}" class="thumbnail img-responsive">
       <i class="fa fa-chevron-down" aria-hidden="true"></i>
     </button>
    <ul class="dropdown-menu" role="menu">
      <li><a href="{{route('users.edit', [Auth::user()->id])}}"><i class="fa fa-user" aria-hidden="true"></i>&nbsp;{{Auth::user()->name}}</a></li>
      <li><a href="{{route('users.edit', [Auth::user()->id])}}#mynominations"><i class="fa fa-trophy" aria-hidden="true"></i>&nbsp;Мои номинации</a></li>
      <li><a href="{{route('users.edit', [Auth::user()->id])}}#myphotos"><i class="fa fa-camera" aria-hidden="true"></i>&nbsp;Мои фото</a></li>
      <li><a href="{{route('users.edit', [Auth::user()->id])}}#myratings"><i class="fa fa-bar-chart" aria-hidden="true"></i>&nbsp;Мои рейтинги</a></li>
      <li><a href="{{route('users.comments', [Auth::user()->id])}}"><i class="fa fa-comment" aria-hidden="true"></i>&nbsp;Мои комментарии</a></li>
      <li><a href="{{route('like.buy', [Auth::user()->id])}}"><i class="fa fa-heart color-red" aria-hidden="true"></i>&nbsp;Купить</a></li>
      @permission('adminpanel_access')
      <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-tachometer" aria-hidden="true"></i>&nbsp;Панель управления</a></li>
      @endpermission @role('testreferee')
      <li><a href="{{route('referee.index')}}"><i class="fa fa-graduation-cap" aria-hidden="true"></i>&nbsp;Судейство</a></li>
      @endrole
      <li class="divider"></li>
      <li>
        <a href="{{ url('/logout') }}" onclick="event.preventDefault();
                                 document.getElementById('logout-form').submit();"><i class="fa fa-sign-out" aria-hidden="true"></i>&nbsp;Выход</a>
      </li>
      <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
        {{ csrf_field() }}
      </form>
    </ul>

  @else
    <button type="button"  data-toggle="modal" data-target="#modalLogin">

      <strong>Вход</strong>
      <i class="fa fa-chevron-down" aria-hidden="true"></i>
    </button>
  @endif
  </div>
    </div>
  </div>

  </div>

resources/views/widget/decor-panel.blade.php
<br>
<div class="row">
  <div class="col-lg-12">

</div>
  @if (Auth::user())
    <a href="{{route('like.buy', [Auth::user()->id])}}" class="decor col-md-2 col-xs-4 text-center">
      <p class="lead color-red"><i class="fa fa-heart" aria-hidden="true"></i></p>
      <p  class="text-muted">Лайки</p>
    </a>

  @else
    <div class="decor col-md-2 col-xs-4 text-center">
      <p class="lead text-muted"><i class="fa fa-heart" aria-hidden="true"></i></p>
      <p  class="text-muted">Лайки</p>
    </div>
  @endif

 <a href="{{url('/nomination')}}" class="decor col-md-2 col-xs-4 text-center">
    <p class="lead color-gold"><i class="fa fa-trophy" aria-hidden="true"></i></p>
    <p  class="text-warning">Номинации</p>
  </a>
  <a href="{{url('/rating')}}" class="decor col-md-2 col-xs-4 text-center">
    <p class="lead color-black"><i class="fa fa-bar-chart" aria-hidden="true"></i></p>
    <p  class="text-danger">Рейтинги</p>
  </a>
  <a href="{{url('/fund')}}" class="decor col-md-2 col-xs-4 text-center">
    <p class="lead color-green-bibikini"><i class="fa fa-money" aria-hidden="true"></i></p>
    <p  class="text-muted">Призы</p>
  </a>
  <a href="{{url('/photo')}}" class="decor col-md-2 col-xs-4 text-center">
    <p class="lead color-blue"><i class="fa fa-camera-retro" aria-hidden="true"></i></p>
    <p  class="text-muted">Фото</p>
  </a>
  <a href="{{url('/competitor')}}" class="decor col-md-2 col-xs-4 text-center">
    <p class="lead"><span class="color-blue"><i class="fa fa-male" aria-hidden="true"></i></span>
      <span class="color-green-bibikini"><i class="fa fa-female" aria-hidden="true"></i></span></p>
    <p  class="text-muted">Участники</p>
  </a>

</div>

resources/views/widget/groups.blade.php
<div class="row groups">
  <hr>
  <div class="col-lg-12">
  <h3>Мы в социальных сетях</h3>
</div>
  <div class="col-md-4">
    <script type="text/javascript" src="//vk.com/js/api/openapi.js?150"></script>
    <!-- VK Widget -->
    <div id="vk_groups"></div>
    <script type="text/javascript">
    VK.Widgets.Group("vk_groups", {mode: 3, "width":300,"height":285}, 158184697);
    </script>
  </div>
  <div class="col-md-4">
    <iframe src="//widget.instagramm.ru/?imageW=2&imageH=2&thumbnail_size=117&type=0&typetext=facefrontru&head_show=1&profile_show=1&shadow_show=1&bg=255,255,255,1&opacity=true&head_bg=46729b&subscribe_bg=ad4141&border_color=c3c3c3&head_title=" allowtransparency="true" frameborder="0" scrolling="no" style="border:none;overflow:hidden;width:260px;height:399px;"></iframe>
  </div>
  <div class="col-md-4">
    <div id="ok_group_widget"></div>
<script>
!function (d, id, did, st) {
  var js = d.createElement("script");
  js.src = "https://connect.ok.ru/connect.js";
  js.onload = js.onreadystatechange = function () {
  if (!this.readyState || this.readyState == "loaded" || this.readyState == "complete") {
    if (!this.executed) {
      this.executed = true;
      setTimeout(function () {
        OK.CONNECT.insertGroupWidget(id,did,st);
      }, 0);
    }
  }}
  d.documentElement.appendChild(js);
}(document,"ok_group_widget","53763345088721",'{"width":300,"height":285}');
</script>
  </div>

  <div class="clearfix"></div>
</div>

resources/views/widget/informer.blade.php
<div class="row">
    <div class="col-lg-12">
        <div class="informer">
                  @foreach ($contents as $content)
                        @if ($content->key == $content_key)
                            {!! $content->content !!}
                        @endif
                  @endforeach
                <p class="pull-left">
                    <button type="button" class="btn btn-danger btn-lg">Закрыть&nbsp; <i class="fa fa-times" aria-hidden="true"></i></button>
                </p>
                <p class="pull-right">
                    <input id="notshow" data-url="{{$cookie_url}}" type="checkbox"> Больше не показывать это сообщение
                </p>
                <div class="clearfix"></div>
        </div>
    </div>

</div>

resources/views/widget/metrika.blade.php
<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter46904676 = new Ya.Metrika({
                    id:46904676,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/46904676" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

resources/views/widget/registration_link.blade.php
@if (!Auth::user())
<div class="alert alert-info alert-block">
    <button type="button" class="close" data-dismiss="alert"><i class="fa fa-minus-square"></i></button>
    <a class="btn btn-primary" href="/register">Регистрация</a>
    <a class="btn btn-danger" href="/help#quick-start">Старт</a>
    <a class="btn btn-success" href="/help">Справка</a>
</div>
@endif

resources/views/widget/social.blade.php
<script src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js"></script>
<script src="//yastatic.net/share2/share.js"></script>
<div class="ya-share2" data-services="vkontakte,facebook,odnoklassniki" data-counter=""></div>

resources/views/widget/table_score_agr.blade.php
<div class="table-responsive">
    <table id="table-referees" class="table scores" data-avg="
    @if(!empty($avgScore))
    {{$avgScore->first()->avgscore}}
   @endif
    "
    data-rating="
    @if(!empty($rating))
    {{$rating}}
   @endif
    "
    >
        @foreach ($referees as $referee)
         <tr>
             <td class="photo">
              <div class="thumbnail">
                @if($referee->user->avatar=='default')
                   @php
                   $referee->user->avatar= asset('assets/img/default/avatar.png');
                   @endphp
                @endif
                  <a href="{{route('users.show', [$referee->user->id])}}"><img src="{{asset($referee->user->avatar)}}" /></a>
              </div>
             </td>
             @if ($referee->review->count() > 0)
              <td class="revize">
              <small><i class="fa fa-eye" aria-hidden="true"></i>&nbsp;{{$referee->review->count()}}</small>
             @else
              <td class="revize no">
              <small><i class="fa fa-eye-slash" aria-hidden="true"></i>&nbsp;0</small>
             @endif
            </td>
             </td>
             @if (!empty($referee->scoreActual->first()->score))
               <td class="score">
                 <small class="score-actual"><i class="fa fa-graduation-cap" aria-hidden="true"></i>&nbsp;{{$referee->scoreActual->first()->score}}</small>
               </td>
               <td class="score">
                 <small>{{ date('d.m.Y', strtotime($referee->scoreActual->first()->created_at)) }}</small>
               </td>
              @else
               <td class="score no">
                 <small><i class="fa fa-graduation-cap" aria-hidden="true"></i>&nbsp;0</small>
                </td>
                <td class="score">
                  <small></small>
                </td>
              @endif
              @if(!empty($lastPhoto) && !empty($referee->scoreActual->first()->score))
                @if($lastPhoto > $referee->scoreActual->first()->created_at)
                 <td class="score no">
                   <small><i class="fa fa-camera" aria-hidden="true"></i></small>
                 </td>
                @else
                 <td class="score">
                   <small></small>
                 </td>
                @endif
              @else
               <td class="score">
                 <small></small>
               </td>
              @endif


             <td class="score">
              <button type="button" class="btn btn-xs btn-info" data-toggle="collapse" data-target="#editdata_{{$referee->id}}">
                  История
              </button>
             </td>


         </tr>
         <tr id="editdata_{{$referee->id}}" class="collapse">

             <td class="td-collapse"></td>
             <td class="td-collapse"></td>
             <td class="score td-collapse">
              @foreach($referee->score as $score)
               @if($score->is_actual == 0)
                <small><i class="fa fa-graduation-cap" aria-hidden="true"></i>&nbsp;{{$score->score}}</small>&nbsp;&nbsp;&nbsp;&nbsp;<small>{{ date('d.m.Y', strtotime($score->created_at)) }}</small>
               <br>
               @else
                <small class="score-actual"><i class="fa fa-graduation-cap" aria-hidden="true"></i>&nbsp;{{$score->score}}</small>&nbsp;&nbsp;&nbsp;&nbsp;<small>{{ date('d.m.Y', strtotime($score->created_at)) }}</small>
                <br>
               @endif
              @endforeach

             </td>
         </tr>
        @endforeach


    </table>
</div>